resources:
  - name: custom_git
    type: GitRepo
    configuration:
      gitProvider: git
      path: ChaitanyaVootla/customYaml
pipelines:
  - name: mixed
    steps:
      # - name: autoImage
      #   type: Bash
      #   configuration:
      #     inputResources:
      #       - name: custom_git
      #     runtime:           
      #       type: image
      #       image:
      #         auto:
      #           language: node
      #           version: "16"
      #   execution:
      #     onExecute:
      #       - node -v
      # - name: customNodeImage
      #   type: Bash
      #   configuration:
      #     inputResources:
      #       - name: custom_git
      #     runtime:           
      #       type: image
      #       image:
      #         custom:
      #           name: node
      #           tag: latest
      #   execution:
      #     onExecute:
      #       - node -v
      # - name: go_build
      #   type: GoBuild
      #   configuration:
      #     inputResources:
      #       - name: custom_git
      #     sourceLocation: .
      #     resolverRepo: go-virtual
      #     noRegistry: true
      #     integrations:
      #       - name: art
      - name: npm_build
        type: NpmBuild
        configuration:
          repositoryName: npm-virtual
          sourceLocation: .
          integrations:
            - name:  art
          inputResources:
            - name: custom_git 
  - name: customNodeImage
    configuration:
      environmentVariables:
        readOnly:
          node_version: "14.21.3"
    steps:
      - name: customNodeImage
        type: Bash
        configuration:
          runtime:           
            type: image
            image:
              custom:
                name: node
                tag: 14.21.3
        execution:
          onExecute:
            - node -v
  - name: ubuntuLatest
    steps:
      - name: customUbuntuImage
        type: Bash
        configuration:
          runtime:           
            type: image
            image:
              custom:
                name: ubuntu
                tag: bionic
        execution:
          onExecute:
            - node -v
  - name: affinity
    steps:
      - name: step_1
        type: Bash
        configuration:
          affinityGroup: "dagroup"
        execution:
          onExecute:
            - echo "step_1"
      - name: step_2
        type: Bash
        configuration:
          affinityGroup: "dagroup"
          inputResources:
            - name: step_1
        execution:
          onExecute:
            - echo "step_2"
