resources:
  - name: custom_git
    type: GitRepo
    configuration:
      gitProvider: git
      path: ChaitanyaVootla/customYaml
pipelines:
  - name: mixed
    steps:
      - name: autoImage
        type: Bash
        configuration:
          inputResources:
            - name: custom_git
          runtime:           
            type: image
            image:
              auto:
                language: node
                version: "16"
        execution:
          onExecute:
            - node -v
      - name: customNodeImage
        type: Bash
        configuration:
          inputResources:
            - name: custom_git
          runtime:           
            type: image
            image:
              custom:
                name: node
                tag: latest
        execution:
          onExecute:
            - node -v
      # - name: ubuntu_latest
      #   type: Bash
      #   configuration:
      #     inputSteps:
      #       - name: customNodeImage
      #     runtime:           
      #       type: image
      #       image:
      #         custom:
      #           name: ubuntu
      #           tag: latest
      #   execution:
      #     onExecute:
      #       - node -v
      # - name: ubuntu_bionic
      #   type: Bash
      #   configuration:
      #     inputSteps:
      #       - name: customNodeImage
      #     runtime:           
      #       type: image
      #       image:
      #         custom:
      #           name: ubuntu
      #           tag: bionic
      #   execution:
      #     onExecute:
      #       - node -v
      - name: build_go
        type: GoBuild
        configuration:
          inputSteps:
            - name: customNodeImage
          sourceLocation: .
          inputResources:
            - name: custom_git
          integrations:
            - name: art
  - name: customNodeImage
    configuration:
      environmentVariables:
        readOnly:
          node_version: "14.21.3"
    steps:
      - name: customNodeImage
        type: Bash
        configuration:
          runtime:           
            type: image
            image:
              custom:
                name: node
                tag: 14.21.3
        execution:
          onExecute:
            - node -v
  - name: ubuntuLatest
    steps:
      - name: customUbuntuImage
        type: Bash
        configuration:
          runtime:           
            type: image
            image:
              custom:
                name: ubuntu
                tag: bionic
        execution:
          onExecute:
            - node -v
