pipelines:
  - name: customImage
    steps:
      - name: autoImage
        type: Bash
        configuration:
          runtime:           
            type: image
            image:
              auto:
                language: node
                version: "16"
        execution:
          onExecute:
            - node -v
      - name: customNodeImage
        type: Bash
        configuration:
          inputSteps:
            - name: autoImage
          runtime:           
            type: image
            image:
              custom:
                name: node
                tag: latest
        execution:
          onExecute:
            - node -v
      - name: customUbuntuImage
        type: Bash
        configuration:
          inputSteps:
            - name: customNodeImage
          runtime:           
            type: image
            image:
              custom:
                name: ubuntu
                tag: latest
        execution:
          onExecute:
            - node -v
