pipelines:
  - name: customImage
    steps:
      - name: customImage
        type: Bash
        configuration:
          runtime:           
            type: image
            image:
              auto:
                language: node
                version: "16"
#               custom:
#                 name: ubuntu
#                 tag: latest
        execution:
          onExecute:
            - echo "executing task command 1"
            - echo "executing task command 2"
