pipelines:
  - name: affinity
    steps:
      - name: step_1
        type: Bash
        configuration:
          affinityGroup: "dagroup"
        execution:
          onExecute:
            - echo "step_1"
            - echo "Running " $pipeline_name "|" $step_name > $shared_workspace/myoutput.txt
            - echo $shared_workspace
            - ls -la $shared_workspace
            - cat $shared_workspace/myoutput.txt
            # - docker images
      - name: step_2
        type: Bash
        configuration:
          affinityGroup: "dagroup"
          inputSteps:
            - name: step_1
        execution:
          onExecute:
            - echo "step_2"
            - echo $shared_workspace
            - ls -la $shared_workspace
            - cat $shared_workspace/myoutput.txt
      - name: step_3
        type: Bash
        configuration:
          affinityGroup: "dagroup"
          inputSteps:
            - name: step_2
        execution:
          onExecute:
            - echo "step_3"
  - name: non_affinity
    steps:
      - name: step_1
        type: Bash
        execution:
          onExecute:
            - echo "step_1"
            - echo "Running " $pipeline_name "|" $step_name > $shared_workspace/myoutput.txt
            - echo $shared_workspace
            - ls -la $shared_workspace
            - cat $shared_workspace/myoutput.txt
            - docker images
      - name: step_2
        type: Bash
        configuration:
          inputSteps:
            - name: step_1
        execution:
          onExecute:
            - echo "step_2"
            - echo $shared_workspace
            - ls -la $shared_workspace
            - cat $shared_workspace/myoutput.txt
      - name: step_3
        type: Bash
        configuration:
          inputSteps:
            - name: step_2
        execution:
          onExecute:
            - echo "step_3"