pipelines:
  - name: customImage
    steps:
      - name: customImage
        type: Bash
        configuration:
          runtime:           
            type: image
            image:
              auto:
                language: node
                version: "16"
#               custom:
#                 name: ubuntu
#                 tag: latest
        execution:
          onExecute:
            - node -v
      - name: customImage2
        type: Bash
        configuration:
          inputSteps:
            - name: customImage
          runtime:           
            type: image
            image:
#               auto:
#                 language: node
#                 version: "12"
              custom:
                name: node
                tag: latest
        execution:
          onExecute:
            - node -v
